[internals]
cache-path = "/tmp/kasuku-cache-3"

[vaults]
planning = { plugins = ["tasks", "dataview"], mount = "/home/geoff/Documents/kasuku" }

[plugins]
tasks = { uri = "localhost:5000/tasks:0.1.0" }
dataview = { uri = "localhost:5000/dataview:0.1.0", config = { tag = "dataview" } }


[events]
'cron::Daily' = [
    "tasks::CleanUp",
    "template::GenerateDaily",
    "fitness::TrackDaily",
]
"tasks::TaskEvent::Delete" = ["growth::Cleanup"]
