[internals]
cache-path = "./cache"

[vaults.planning]
plugins = ["tasks"]
mount = "/home/geoff/Documents/kasuku"
file_types = ["md"]
# budget = { plugins = ["tasks", "finance", "schedule"], mount = "./Bills" }
# entertainment = { plugins = ["files", "spotify", "audible"], mount = "./Media" }

[plugins]
tasks = { uri = "localhost:5000/tasks:v8", config = "checkbox" }
# notes = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/notes" }
# fitness = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/fitness" }
# finance = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/finance" }
# files = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/files" }
# schedule = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/schedule" }
# growth = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/growth" }
# password-manager = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/password-manager", headless = true }
# encryption = { uri = "ghcr.io/geofmureithi/kasuku/@plugins/password-manager", headless = true }


[web-components]
button = ""


[events]
'cron::Daily' = [
    "files::CleanUp",
    "tasks::GenerateDaily",
    "fitness::TrackDaily",
]
"tasks::TaskEvent::Delete" = ["growth::Cleanup"]
