[package]
name = "context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["backend"]
backend = ["tokio", "async-trait", "kasuku-database", "distribution"]

[dependencies]
anyhow = "1"
types = { path = "../../core/types" }
distribution = { path = "../distribution", optional = true }
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
kasuku-database = { path = "../database", optional = true }
serde = "1"
plugy = { git = "https://github.com/geofmureithi/plugy.git", branch = "chore/msgpack-codec" }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
plugy = { git = "https://github.com/geofmureithi/plugy.git", branch = "chore/msgpack-codec", default-features = false, features = [
    "runtime",
] }
sqlparser = "0.30"
tracing = "0.1"
